### ISSUE TITLE
Checklist to minimum completed port for deployment

### ISSUE THREAD

**Issue by ky28059** [ky28059/GRTWebsite2.0#1]
### Home (`/`):
- [x] Nav
- [x] Slideshow
- [x] About (`#about`)
- [x] Timeline
- [x] Sponsors (`#sponsors`)

### Updates (`/updates`):
- [x] Index, system for automatic generation

### FIRST (`/FIRST`):
- [x] Index
- [x] Accolades *(minimum requirements satisfied but eventually add 2022 and 2021(?) awards)*
- [x] 2019
- [x] 2018
- [x] 2016 *(missing text in first section; finish paragraph, then mark as done)*
- [x] 2015
- [x] 2014
- [x] 2013
- [x] 2012

### Subgroups (`/subgroups`):
- [x] Index
- [x] Controls *(minimums ok, but add training + auton? + more on elextrical later)*
- [x] DT *(finish swerve section, then minimums ok; add training section + swerve module photos later)*
- [x] CNC
- [x] Pneumatics *(minimums ok, but add more content; contact pneumatics lead)*
- [x] Animation
- [x] Welding *(minimums ok, but update COVID response)*
- [x] Business *(minimums ok, but add more content)*

### Mentors (`/mentors`):
- [x] Index *(missing added section displaying mentors)*
- [x] Kristina *(minimums ok, but in general for all of these check image dates for captions)*
- [x] Seth
- [x] Karl
- [x] Phil
- [x] Zach

### Join (`/join`):
- [x] Index

### Summer (`/summer`):
- [x] Index *(minimums ok, but expand on blurb later)*

### Donations (`/donations`):
- [x] Index
